package student;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CityShortName {
	public static Map getCityCode() {
		Map<Integer,List<String>> map = new HashMap<>();
 
		ArrayList<String> list1=new ArrayList<String>();  
		list1.add("---Select---");  
	    list1.add("KAPATA");  
	    list1.add("KAMATA");    
	    list1.add("KAMANA");    
	    list1.add("KHAPHANA");
	    list1.add("KHABADA");
	    list1.add("KHALAPHA");
	    list1.add("SADANA");
	    list1.add("SAPABA");
	    list1.add("SABATA");
	    list1.add("SALANA");
	    list1.add("TANANA");
	    list1.add("DAPHAYA");
	    list1.add("NAMANA");
	    list1.add("PATAAH");
	    list1.add("PANADA");
	    list1.add("PAWANA");
	    list1.add("PHAKANA");
	    list1.add("BAMANA");
	    list1.add("MAKATA");
	    list1.add("MAKANA");
	    list1.add("MAKHABA");
	    list1.add("MASANA");
	    list1.add("MANYANA");
	    list1.add("MAMANA");
	    list1.add("MALANA");
	    list1.add("YAKANA");
	    list1.add("YABAYA");
	    list1.add("LAGANA");
	    list1.add("WAMANA");
	    list1.add("HAPANA");
	    list1.add("AHGAYA");
	    map.put(1, list1);
	    //System.out.println(map);  
 
	    ArrayList<String> list2=new ArrayList<String>();  
	    list2.add("---Select---"); 
	    list2.add("DAMASA");  
	    list2.add("PHASANA");    
	    list2.add("PHAYASA");    
	    list2.add("BALAKHA"); 
	    list2.add("MASANA"); 
	    list2.add("YATHANA");
	    list2.add("LAKANA");
	    map.put(2, list2);
 
	    ArrayList<String> list3=new ArrayList<String>();
	    list3.add("---Select---"); 
	    list3.add("KAKAYA");
	    list3.add("KASAKA");
	    list3.add("KADANA");
	    list3.add("KAMAMA");
	    list3.add("SAKALA");
	    list3.add("PAKANA");
	    list3.add("PHAAHNA");
	    list3.add("BAGALA");
	    list3.add("BATHASA");
	    list3.add("BAAHNA");
	    list3.add("MAWATA");
	    list3.add("YAYATHA");
	    list3.add("LABANA");
	    list3.add("LATHANA");
	    list3.add("WALAMA");
	    list3.add("THATAKA");
	    list3.add("THATANA");
	    map.put(3, list3);
 
	    ArrayList<String> list4=new ArrayList<String>();
	    list4.add("---Select---"); 
	    list4.add("KAKHANA");
	    list4.add("KAPALA");
	    list4.add("SAMANA");
	    list4.add("TAZANA");
	    list4.add("TATANA");
	    list4.add("HTATALA");
	    list4.add("PALAWA");
	    list4.add("PHALANA");
	    list4.add("MATANA");
	    list4.add("MATAPA");
	    list4.add("YAKHADA");
	    list4.add("YAZANA");
	    list4.add("HAKHANA");
	    map.put(4, list4);
 
	    ArrayList<String> list5=new ArrayList<String>();
	    list5.add("---Select---"); 
	    list5.add("KANANA");
	    list5.add("KABALA");
	    list5.add("KAMATA");
	    list5.add("KALATA");
	    list5.add("KALAHTA");
	    list5.add("KALANA");
	    list5.add("KALAWA");
	    list5.add("KATANA");
	    list5.add("KHATANA");
	    list5.add("KHAPANA");
	    list5.add("KHAOUTA");
	    list5.add("KHAOUNA");
	    list5.add("NGAZANA");
	    list5.add("SAKANA");
	    list5.add("HSAMAYA");
	    list5.add("HSALAKA");
	    list5.add("TASANA");
	    list5.add("TAMANA");
	    list5.add("HTAKHANA");
	    list5.add("HTAPAKHA");
	    list5.add("DAPAYA");
	    list5.add("DAHANA");
	    list5.add("NAYANA");
	    list5.add("PAHSANA");
	    list5.add("PALANA");
	    list5.add("PALABA");
	    list5.add("PHAPANA");
	    list5.add("BAMANA");
	    list5.add("BATALA");
	    list5.add("MAKANA");
	    list5.add("MAPALA");
	    list5.add("MAMATA");
	    list5.add("MAMANA");
	    list5.add("MARANA");
	    list5.add("MALANA");
	    list5.add("MATANA");
	    list5.add("RAMAPA");
	    list5.add("YABANA");
	    list5.add("YAOUNA");
	    list5.add("LAYANA");
	    list5.add("LAHANA");
	    list5.add("WALANA");
	    list5.add("WATHANA");
	    list5.add("HAMALA");
	    list5.add("AHTANA");
	    list5.add("AHYATA");	    
	    map.put(5, list5);
 
	    ArrayList<String> list6=new ArrayList<String>();
	    list6.add("---Select---"); 
	    list6.add("KASANA");
	    list6.add("KAYAYA");
	    list6.add("KALAAH");
	    list6.add("KATHANA");
	    list6.add("KATHATA");
	    list6.add("KHAMAKA");
	    list6.add("TATHAYA");
	    list6.add("HTAWANA");
	    list6.add("PAKAMA");
	    list6.add("PALANA");
	    list6.add("PALATA");
	    list6.add("BAPANA");
	    list6.add("MATANA");
	    list6.add("MAMANA");
	    list6.add("MAAHNA");
	    list6.add("MAAHYA");
	    list6.add("YAPHANA");
	    list6.add("LALANA");
	    list6.add("THARAKHA");
	    map.put(6, list6);
 
	    ArrayList<String> list7=new ArrayList<String>();
	    list7.add("---Select---"); 
	    list7.add("KAKANA");
	    list7.add("KATAKHA");
	    list7.add("KAPAKA");
	    list7.add("KAWANA");
	    list7.add("ZAKANA");
	    list7.add("NYALAPA");
	    list7.add("TANGANA");
	    list7.add("HTATAPA");
	    list7.add("DAOUNA");
	    list7.add("NATALA");
	    list7.add("PAKHATA");
	    list7.add("PAKHANA");
	    list7.add("PATATA");
	    list7.add("PATANA");
	    list7.add("PAMANA");
	    list7.add("PHAMANA");
	    list7.add("MANYANA");
	    list7.add("MALANA");
	    list7.add("YAKANA");
	    list7.add("YATANA");
	    list7.add("YATAYA");
	    list7.add("LAPATA");
	    list7.add("WAMANA");
	    list7.add("THAKANA");
	    list7.add("THANAPA");
	    list7.add("THAWATA");
	    list7.add("AHTANA");
	    list7.add("AHPHANA");
	    map.put(7, list7);
 
	    ArrayList<String> list8=new ArrayList<String>();
	    list8.add("---Select---"); 
	    list8.add("KAHTANA");
	    list8.add("KAMANA");
	    list8.add("KHAMANA");
	    list8.add("GAGANA");
	    list8.add("NGAPHANA");
	    list8.add("SATAYA");
	    list8.add("SALANA");
	    list8.add("SAPAWA");
	    list8.add("SAPHANA");
	    list8.add("SAMANA");
	    list8.add("TATAKA");
	    list8.add("HTALANA");
	    list8.add("NAMANA");
	    list8.add("PAKHAKA");
	    list8.add("PAPHANA");
	    list8.add("PAMANA");
	    list8.add("MAKANA");
	    list8.add("MATANA");
	    list8.add("MAHTANA");
	    list8.add("MABANA");
	    list8.add("MAMANA");
	    list8.add("MALANA");
	    list8.add("MATHANA");
	    list8.add("YASAKA");
	    list8.add("YANAKHA");
	    list8.add("THAYANA");
	    list8.add("AHLANA");
	    map.put(8, list8);
 
	    ArrayList<String> list9=new ArrayList<String>();
	    list9.add("---Select---"); 
	    list9.add("KASANA");
	    list9.add("KAPATA");
	    list9.add("KHAMASA");
	    list9.add("KHAAHZA");
	    list9.add("NGAZANA");
	    list9.add("NGATHAYA");
	    list9.add("SAKATA");
	    list9.add("SAKANA");
	    list9.add("ZABATHA");
	    list9.add("ZAYATHA");
	    list9.add("NYAOUNA");
	    list9.add("TAKATA");
	    list9.add("TAKANA");
	    list9.add("TATAU");
	    list9.add("TATHANA");
	    list9.add("DAKHATHA");
	    list9.add("NATHAKA");
	    list9.add("PAKAKHA");
	    list9.add("PABATHA");
	    list9.add("PABANA");
	    list9.add("PAMANA");
	    list9.add("PATHAKA");
	    list9.add("PAOULA");
	    list9.add("MAKANA");
	    list9.add("MAKHANA");
	    list9.add("MATAYA");
	    list9.add("MAHTALA");
	    list9.add("MANATA");
	    list9.add("MANAMA");
	    list9.add("MAMANA");
	    list9.add("MAYATA");
	    list9.add("MAYAMA");
	    list9.add("MALANA");
	    list9.add("MATANA");
	    list9.add("MAHAMA");
	    list9.add("YAMATHA");
	    list9.add("LAWANA");
	    list9.add("WATANA");
	    list9.add("THASANA");
	    list9.add("THAPAKA");
	    list9.add("AHMAZA");
	    list9.add("AHMARA");
	    list9.add("AUTATHA");
	    map.put(9, list9);
 
	    ArrayList<String> list10=new ArrayList<String>();
	    list10.add("---Select---"); 
	    list10.add("KAHTANA");
	    list10.add("KAKHAMA");
	    list10.add("KHASANA");
	    list10.add("KHAZANA");
	    list10.add("PAMANA");
	    list10.add("BALANA");
	    list10.add("MADANA");
	    list10.add("MALAMA");
	    list10.add("YAMANA");
	    list10.add("LAMANA");
	    list10.add("THAHTANA");
	    list10.add("THAPHARA");
	    list10.add("RAMANA");
	    list10.add("THAPHAYA");
	    map.put(10, list10);
 
	    ArrayList<String> list11=new ArrayList<String>();
	    list11.add("---Select---"); 
	    list11.add("KATANA");
	    list11.add("KATALA");
	    list11.add("KAPHANA");
	    list11.add("GAMANA");
	    list11.add("SATANA");
	    list11.add("TAKANA");
	    list11.add("TAPAWA");
	    list11.add("PANAKA");
	    list11.add("PANATA");
	    list11.add("BATHATA");
	    list11.add("MATANA");
	    list11.add("MAPANA");
	    list11.add("MAPANA");
	    list11.add("MAAHTA");
	    list11.add("NAAHNA");
	    list11.add("MAUNA");
	    list11.add("YABANA");
	    list11.add("YABANA");
	    list11.add("YATHATA");
	    list11.add("THATANA");
	    list11.add("AHMANA");
	    map.put(11, list11);
 
	    ArrayList<String> list12=new ArrayList<String>();
	    list12.add("---Select---"); 
	    list12.add("KAKAKA");
	    list12.add("KAKHAKA");
	    list12.add("KATATA");
	    list12.add("KANATA");
	    list12.add("KAMATA");
	    list12.add("KAMANA");
	    list12.add("KAMAYA");
	    list12.add("KHAYANA");
	    list12.add("SAKHANA");
	    list12.add("SAKAKHA");
	    list12.add("SAKANA");
	    list12.add("TAKANA");
	    list12.add("TATATA");
	    list12.add("TATAHTA");
	    list12.add("TATANA");
	    list12.add("TAMANA");
	    list12.add("HTATAPA");
	    list12.add("DAGAYA");
	    list12.add("DAGATA");
	    list12.add("DAGASA");
	    list12.add("DAGANA");
	    list12.add("DAGAMA");
	    list12.add("DAPANA");
	    list12.add("DALANA");
	    list12.add("PAZATA");
	    list12.add("PABATA");
	    list12.add("BATAHTA");
	    list12.add("BAHANA");
	    list12.add("MAGATA");
	    list12.add("MAGADA");
	    list12.add("MABANA");
	    list12.add("MARAKA");
	    list12.add("YAKANA");
	    list12.add("YAPATHA");
	    list12.add("LAKANA");
	    list12.add("LAMATA");
	    list12.add("LAMANA");
	    list12.add("LATHANA");
	    list12.add("LATHAYA");
	    list12.add("THAKATA");
	    list12.add("THAKHANA");
	    list12.add("THAGAKA");
	    list12.add("THALANA");
	    list12.add("AHSANA");
	    list12.add("AHLANA");
	    list12.add("OUKATA");
	    list12.add("OUKAMA");
	    map.put(12, list12);
 
	    ArrayList<String> list13=new ArrayList<String>();
	    list13.add("---Select---"); 
	    list13.add("KAKANA");
	    list13.add("KAKHANA");
	    list13.add("KATATA");
	    list13.add("KATANA");
	    list13.add("KATALA");
	    list13.add("KAMANA");
	    list13.add("KALATA");
	    list13.add("KALAHTA");
	    list13.add("KALADA");
	    list13.add("KALANA");
	    list13.add("KATHANA");
	    list13.add("KAHANA");
	    list13.add("KHAYAHA");
	    list13.add("KHALANA");
	    list13.add("SASANA");
	    list13.add("NYAYANA");
	    list13.add("TAKANA");
	    list13.add("TAKHALA");
	    list13.add("TATANA");
	    list13.add("TAMANYA");
	    list13.add("TAYANA");
	    list13.add("TALANA");
	    list13.add("NAKHATA");
	    list13.add("NAKHANA");
	    list13.add("NASANA");
	    list13.add("NAHSANA");
	    list13.add("NATANA");
	    list13.add("NATAYA");
	    list13.add("NAPHANA");
	    list13.add("NAMATA");
	    list13.add("PASANA");
	    list13.add("PASATA");
	    list13.add("PATAYA");
	    list13.add("PAPAKA");
	    list13.add("PARANA");
	    list13.add("PALATA");
	    list13.add("PALAHTA");
	    list13.add("PALANA");
	    list13.add("PAWANA");
	    list13.add("PHAKHANA");
	    list13.add("MAKATA");
	    list13.add("MAKAHTA");
	    list13.add("MAKANA");
	    list13.add("MAKHATA");
	    list13.add("MAKHANA");
	    list13.add("MANGANA");
	    list13.add("MASANA");
	    list13.add("MAHSATA");
	    list13.add("MAHSANA");
	    list13.add("MATATA");
	    list13.add("MATANA");
	    list13.add("MAHTATA");
	    list13.add("MAHTANA");
	    list13.add("MANATA");
	    list13.add("MANANA");
	    list13.add("MAPATA");
	    list13.add("MAPAHTA");
	    list13.add("MAPANA");
	    list13.add("MAPHATA");
	    list13.add("MAPHANA");
	    list13.add("MABANA");
	    list13.add("MAMATA");
	    list13.add("MAMAHTA");
	    list13.add("MAMANA");
	    list13.add("MARATA");
	    list13.add("MARAHTA");
	    list13.add("MARANA");
	    list13.add("MAYATA");
	    list13.add("MAYANA");
	    list13.add("MALATA");
	    list13.add("MALANA");
	    list13.add("MAHAYA");
	    list13.add("YANGANA");
	    list13.add("YASANA");
	    list13.add("LAKANA");
	    list13.add("LAKHATA");
	    list13.add("LAKHANA");
	    list13.add("LAYANA");
	    list13.add("LALANA");
	    list13.add("THANANA");
	    list13.add("THAPANA");
	    list13.add("HAPATA");
	    list13.add("HAPANA");
	    list13.add("HAMANA");
	    list13.add("AHTANA");	    
	    map.put(13, list13);
 
	    ArrayList<String> list14=new ArrayList<String>();
	    list14.add("---Select---"); 
	    list14.add("KAKAHTA");
	    list14.add("KAKANA");
	    list14.add("KAKHANA");
	    list14.add("KAPANA");
	    list14.add("KALANA");
	    list14.add("NGASANA");
	    list14.add("NGAPATA");
	    list14.add("NGAYAKA");
	    list14.add("NGATHAKHA");
	    list14.add("ZALANA");
	    list14.add("NYATANA");
	    list14.add("DADAYA");
	    list14.add("DANAPHA");
	    list14.add("PASALA");
	    list14.add("PATANA");
	    list14.add("PATHANA");
	    list14.add("PATHAYA");
	    list14.add("PHAPANA");
	    list14.add("BAKALA");
	    list14.add("MAMAKA");
	    list14.add("MAMANA");
	    list14.add("MAAHNA");
	    list14.add("MAAHPA");
	    list14.add("YAKANA");
	    list14.add("YATHAYA");
	    list14.add("LAPATA");
	    list14.add("LAMANA");
	    list14.add("WAKHAMA");
	    list14.add("THAPANA");
	    list14.add("HAKAKA");
	    list14.add("HATHATA");
	    list14.add("AHGAPA");
	    list14.add("AHMATA");
	    list14.add("AHMANA");
	    map.put(14, list14);
 
 
	    return map;
	}

	public static void main(String args[]){  
		new CityShortName();
	}  
}
